Exploration
===========

Project startup
---------------

Setting knitr options.

``` {r knitr_options}
require(knitr)
opts_knit$set(root.dir="..")
opts_chunk$set(fig.path="../graphs/expl-")
```

Load project with ProjectTemplate.

```{r load_project, warning=FALSE}
require('ProjectTemplate')
load.project()
```

Interest Rate
-------------

```{r rate_summary}
summary(loansData$Interest.Rate)
```

```{r rate_boxplot, fig.height=5, fig.width=5}
boxplot(loansData$Interest.Rate)
```

Interest Rate and Amount Funded
-------------------------------

```{r rate_funded_plot, fig.height=5, fig.width=5}
plot(loansData$Amount.Funded.By.Investors, loansData$Interest.Rate, pch=19, cex=0.5)
lmAmountFunded <- lm(loansData$Interest.Rate ~ loansData$Amount.Funded.By.Investors)
lines(loansData$Amount.Funded.By.Investors, lmAmountFunded$fitted,col="red",lwd=3)
```

```{r rate_funded_lm_summary}
summary(lmAmountFunded)
```

Interest Rate and Loan Length
-----------------------------

```{r rate_length_summary}
tapply(loansData$Interest.Rate, as.factor(loansData$Loan.Length.Months), summary)
```

```{r rate_length_boxplot, fig.height=5, fig.width=5}
boxplot(loansData$Interest.Rate ~ as.factor(loansData$Loan.Length.Months))
```

Interest Rate and Loan Purpose
------------------------------

```{r rate_purpose_summary}
tapply(loansData$Interest.Rate, as.factor(loansData$Loan.Purpose), summary)
```

```{r rate_purpose_boxplot, fig.height=5, fig.width=10}
rateByPurpose = data.frame(Rate = loansData$Interest.Rate, Purpose = loansData$Loan.Purpose)
rateByPurpose$Purpose <- with(rateByPurpose, reorder(Purpose, Rate, median, na.rm = TRUE))
boxplot(Rate ~ Purpose, data = rateByPurpose, xaxt = "n")
loansByPurpose <- table(rateByPurpose$Purpose)
axis(1, las=2, at = 1:nrow(loansByPurpose), labels = names(loansByPurpose))
```

Interest Rate and Debt to Income Ratio
--------------------------------------

```{r rate_diratio_plot, fig.height=5, fig.width=5}
plot(loansData$Debt.To.Income.Ratio, loansData$Interest.Rate, pch=19, cex=0.5)
lmD2IRatio <- lm(loansData$Interest.Rate ~ loansData$Debt.To.Income.Ratio)
lines(loansData$Debt.To.Income.Ratio, lmD2IRatio$fitted,col="red",lwd=3)
```

```{r rate_diratio_lm_summary}
summary(lmD2IRatio)
```

Interest Rate and State
-----------------------

```{r rate_state_summary}
tapply(loansData$Interest.Rate, as.factor(loansData$State), summary)
```

```{r rate_state_boxplot, fig.height=5, fig.width=10}
rateByState = data.frame(Rate = loansData$Interest.Rate, State = loansData$State)
rateByState$State <- with(rateByState, reorder(State, Rate, median, na.rm = TRUE))
boxplot(Rate ~ State, data = rateByState, xaxt = "n")
loansByState <- table(rateByState$State)
axis(1, las=2, at = 1:nrow(loansByState), labels = names(loansByState))
```

Interest Rate and Home Ownership
--------------------------------

```{r rate_ownership_summary}
tapply(loansData$Interest.Rate, as.factor(loansData$Home.Ownership), summary)
```

```{r rate_ownership_boxplot, fig.height=5, fig.width=10}
rateByHomeOwnership = data.frame(Rate = loansData$Interest.Rate, HomeOwnership = loansData$Home.Ownership)
rateByHomeOwnership$HomeOwnership <- with(rateByHomeOwnership, reorder(HomeOwnership, Rate, median, na.rm = TRUE))
boxplot(Rate ~ HomeOwnership, data = rateByHomeOwnership, xaxt = "n")
loansByHomeOwnership <- table(rateByHomeOwnership$HomeOwnership)
axis(1, las=2, at = 1:nrow(loansByHomeOwnership), labels = names(loansByHomeOwnership))
```

Interest Rate and Monthly Income
--------------------------------

```{r rate_income_plot, fig.height=5, fig.width=5}
withoutMonthlyIncomeNA <- loansData[!is.na(loansData$Monthly.Income),]
plot(withoutMonthlyIncomeNA$Monthly.Income, withoutMonthlyIncomeNA$Interest.Rate, pch=19, cex=0.5, log="x")
lmMonthlyIncome <- lm(withoutMonthlyIncomeNA$Interest.Rate ~ log(withoutMonthlyIncomeNA$Monthly.Income))
lines(withoutMonthlyIncomeNA$Monthly.Income, lmMonthlyIncome$fitted, col="red", lwd=3)
```

```{r rate_income_lm_summary}
summary(lmMonthlyIncome)
```

Interest Rate and FICO Range
----------------------------

```{r rate_fico_summary}
tapply(loansData$Interest.Rate, as.factor(loansData$FICO.Range), summary)
```

```{r rate_fico_boxplot, fig.height=5, fig.width=10}
rateByFICORange = data.frame(Rate = loansData$Interest.Rate, FICORange = loansData$FICO.Range)
#rateByFICORange$FICORange <- with(rateByFICORange, reorder(FICORange, Rate, median, na.rm = TRUE))
boxplot(Rate ~ FICORange, data = rateByFICORange, xaxt = "n")
loansByFICORange <- table(rateByFICORange$FICORange)
axis(1, las=2, at = 1:nrow(loansByFICORange), labels = names(loansByFICORange))
```

```{r rate_fico_median_plot, fig.height=5, fig.width=5}
plot(loansData$FICO.Median, loansData$Interest.Rate, pch=19, cex=0.5)
lmFICORate <- lm(loansData$Interest.Rate ~ loansData$FICO.Median)
lines(loansData$FICO.Median, lmFICORate$fitted,col="red",lwd=3)
```

```{r rate_fico_median_lm_summary}
summary(lmFICORate)
```

Interest Rate and Open Credit Lines
-----------------------------------

```{r rate_lines_plot, fig.height=5, fig.width=5}
withoutOpenCreditLinesNA <- loansData[!is.na(loansData$Open.CREDIT.Lines),]
plot(withoutOpenCreditLinesNA$Open.CREDIT.Lines, withoutOpenCreditLinesNA$Interest.Rate, pch=19, cex=0.5)
lmOpenCreditLines <- lm(withoutOpenCreditLinesNA$Interest.Rate ~ withoutOpenCreditLinesNA$Open.CREDIT.Lines)
lines(withoutOpenCreditLinesNA$Open.CREDIT.Lines, lmOpenCreditLines$fitted,col="red",lwd=3)
```

```{r rate_lines_lm_summary}
summary(lmOpenCreditLines)
```

Interest Rate and Revolving Credit Balance
------------------------------------------

```{r rate_revolving_plot, fig.height=5, fig.width=5}
withoutRevolvingCreditBalanceNA <- loansData[!is.na(loansData$Revolving.CREDIT.Balance)
                                             & loansData$Revolving.CREDIT.Balance > 0,]
plot(withoutRevolvingCreditBalanceNA$Revolving.CREDIT.Balance, withoutRevolvingCreditBalanceNA$Interest.Rate, pch=19, cex=0.5, log="x")
lmRevolvingCreditBalance <- lm(withoutRevolvingCreditBalanceNA$Interest.Rate ~ log(withoutRevolvingCreditBalanceNA$Revolving.CREDIT.Balance))
lines(withoutRevolvingCreditBalanceNA$Revolving.CREDIT.Balance, lmRevolvingCreditBalance$fitted, col="red", lwd=3)
```

```{r rate_revolving_lm_summary}
summary(lmRevolvingCreditBalance)
```

Interest Rate and Inquiries in the Last 6 Months
------------------------------------------------

```{r rate_inquiries_plot, fig.height=5, fig.width=5}
withoutInquiriesNA <- loansData[!is.na(loansData$Inquiries.in.the.Last.6.Months),]
plot(withoutInquiriesNA$Inquiries.in.the.Last.6.Months, withoutInquiriesNA$Interest.Rate, pch=19, cex=0.5)
lmInquiries <- lm(withoutInquiriesNA$Interest.Rate ~ withoutInquiriesNA$Inquiries.in.the.Last.6.Months)
lines(withoutInquiriesNA$Inquiries.in.the.Last.6.Months, lmInquiries$fitted, col="red", lwd=3)
```

```{r rate_inquiries_lm_summary}
summary(lmInquiries)
```

Interest Rate and Employment Length
-----------------------------------

```{r rate_employment_plot, fig.height=5, fig.width=5}
withoutEmploymentLengthNA <- loansData[!is.na(loansData$Employment.Length),]
plot(withoutEmploymentLengthNA$Employment.Length, withoutEmploymentLengthNA$Interest.Rate, pch=19, cex=0.5)
lmEmploymentLength <- lm(withoutEmploymentLengthNA$Interest.Rate ~ withoutEmploymentLengthNA$Employment.Length)
lines(withoutEmploymentLengthNA$Employment.Length, lmEmploymentLength$fitted, col="red", lwd=3)
```

```{r rate_employment_lm_summary}
summary(lmEmploymentLength)
```
